In [54]:
import sklearn
import numpy as np

In [55]:
from sklearn.datasets import load_iris
iris = load_iris()

In [56]:
iris.keys()

['target_names', 'data', 'target', 'DESCR', 'feature_names']

In [118]:
X = iris.data[:,[2,3]]
y = iris.target

In [107]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=0)

In [111]:
class KMeans:
    
    def __init__(self,means):
        self.means = means
    
    def classify(self,xdata,ydata,to_classify):
        prediction = np.zeros(len(to_classify))
        for k in range(len(to_classify)):
            distance = np.zeros(len(xdata))
            for i in range(len(xdata)):
                for j in range(len(xdata[0])):
                    distance[i] += np.power(xdata[i,j] - to_classify[k,j],2)
                distance[i] = np.power(distance[i],0.5)
            nearest = np.argsort(distance)[:self.means]
            nearest_prediction = np.zeros(len(nearest))
            for l in range(len(nearest)):
                
            prediction[k] = ydata[np.argmin(distance)]
        return prediction  

In [121]:
model = KMeans(1)
classify = np.array([[1.4,0.2],[1.4,0.3],[5.1,1.9]])

In [122]:
model.classify(X,y,classify)

array([ 0.,  0.,  2.])

In [124]:
y_pred = model.classify(X_train,y_train,X_test)

from sklearn.metrics import accuracy_score
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

Accuracy: 0.97


In [127]:
x = np.array([4,2,3,1])
x

array([4, 2, 3, 1])

In [132]:
np.argsort(x)

array([3, 1, 2, 0])